[tool.ruff]
line-length = 88 
indent-width = 4
extend-include = ["*.ipynb"]

# flake like
[tool.ruff.lint]
extend-ignore = ["T100", "E402", "E741"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"


[tool.mypy]
ignore_missing_imports = true