inherit_from: configs/pointcloud/room_combine.yaml
data:
  classes: ['']
  path: data/demo/synthetic_room_dataset
  pointcloud_n: 10000
  points_file: points_iou
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  pointcloud_chamfer_file: pointcloud
  multi_files: 10
  voxels_file: null
training:
  out_dir: out/demo_syn_room
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud/room_combine.pt
generation:
  generation_dir: generation
